config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :cookbooks
  end 
  
  resources :ingredients

  get 'recipes/search' => 'recipes#search'
  resources :recipes

  get 'welcome/hello'
  get 'about/index'

  root :to => "welcome#index"

  post 'recipes/command_detect', to: "recipes#command_detect"

  resources :ingredients, only: [] do
    get :autocomplete_ingredient_name, :on => :collection
  end

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', :as => :signout

  get 'add_recipe_to_cookbook' => 'recipe_cookbooks#add_recipe_to_cookbook', as: "add_recipe_to_cookbook"

end

app/models/recipe.rb
class MyValidator < ActiveModel::Validator
  def validate(new_recipe)
    if new_recipe.title.length < 2
      new_recipe.errors[:base] << "Must have a valid title."
    end
    new_recipe.recipe_ingredient_units.each do |riu|
      if riu.ingredient.name.length < 1 && !new_recipe.errors[:base].include?("Ingredients must have a valid name.")
        new_recipe.errors[:base] << "Ingredients must have a valid name."
      end 
      # if riu.unit.unit.length < 1 && !new_recipe.errors[:base].include?("Ingredients must have a valid unit.")
      #   new_recipe.errors[:base] << "Ingredients must have a valid unit."
      # end 
    end 
    new_recipe.directions.each do |direction|
      if direction.description.length < 2 && !new_recipe.errors[:base].include?("Directions must have a valid description.")
        new_recipe.errors[:base] << "Directions must have a valid description."
      end 
    end 
  end 
end 

class Recipe < ActiveRecord::Base
  has_many :recipe_cookbooks
  has_many :cookbooks, through: :recipe_cookbooks
  belongs_to :creator, class_name: "User"
  has_many :directions
  has_many :recipe_ingredient_units
  has_many :ingredients, through: :recipe_ingredient_units

  validates_with MyValidator

  # Paperclip (upload image)
  has_attached_file :recipe_image , :styles => { :medium => "250x250>" },
                    # :default_url => "/images/:style/bullet.png",
                    # :default_url => ":rails_root/public/simon_point.jpg",
                    # url for images
                    :url => "/assets/recipes/:id/:basename.:extension"
                    # :url => "https://messychefrecipeimage.s3.amazonaws.com"
                    # path to store images
                    # :path => ":rails_root/public/assets/recipes/:id/:basename.:extension"
  # validates_attachment_content_type :recipe_image, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :recipe_image, :content_type => ['image/jpeg', 'image/png']

  def make_rius_from_params(recipe_params)
    recipe_params[:recipe_ingredient_units].each do |riuId, hash|
      # find or create ingredients & units, associate to recipe
      @ingredient = Ingredient.find_or_create_by(name: hash[:ingredient].downcase.strip.gsub(/\s+/, " "))
      @unit = Unit.find_or_create_by(unit: hash[:unit].downcase.strip.gsub(/\s+/, " "))
      self.recipe_ingredient_units.build(ingredient_id: @ingredient.id, unit_id: @unit.id, amount: hash[:amount])
    end
  end

  def make_directions_from_params(recipe_params)
    recipe_params[:directions].each.with_index do |hash, index|
      # create directions, associate to recipe
      self.directions.build(:sequence => index+1, :description => hash[1][:description])
    end
  end 

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all.order("created_at DESC")
  end

  def search
    @recipes_all = Recipe.all

    search_term = params[:q].downcase 
    multiple_search_terms = search_term.split(/,|\s/).reject { |i| i==""}
    
    @recipes = []

    if search_term == ""         # if search query is blank
      @recipes = @recipes_all
    else                                  # if search query is not blank
      multiple_search_terms.each do |search|
       @recipes << Recipe.where("lower(description) like '%#{search}%' or lower(title) like '%#{search}%'")
      end    
    end

    @recipes = @recipes.flatten

    render "recipes/index"
  end


  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    # set creator_id to user
  end

  # GET /recipes/1/edit
  def edit
  end

  def command_detect
    message = params[:cmd]
    wit = Wit::Client.new ENV["WIT_AI_TOKEN"]
    results = wit.message(message)
    @intent = results["outcomes"][0]["intent"]
    @entity = results["outcomes"][0]["entities"]
    @query = @entity.flatten.flatten.to_s
    @confidence = results["outcomes"][0]["confidence"]
    
    
    if @confidence >= 0.50 && @intent == "directions" && @entity.keys.first == "next" 
        render json: "next"

    elsif @confidence >= 0.50 && @intent == "backward" && @entity.keys.first == "back"
        render json: "back"

    elsif @confidence >= 0.50 && @intent == "search"
        render json: "search #{@query}"

    else
        render json: ""
    end
  end

  # POST /recipes
  # POST /recipes.json
  def create 
    
    # setup new instance
    @recipe = Recipe.new(
      :title => recipe_params[:title],
      :description => recipe_params[:description],
      :recipe_image => recipe_params[:recipe_image],
      :creator_id => current_user.id
    )
    @recipe.make_rius_from_params(recipe_params) if recipe_params[:recipe_ingredient_units].size > 0
    @recipe.make_directions_from_params(recipe_params) if recipe_params[:directions].size > 0

    respond_to do |format|
      if @recipe.save
        if params[:add_to_cookbook] == "yes"
          current_user.cookbooks.first.recipes << @recipe
          current_user.save
        end 
        format.html { redirect_to recipes_path, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    @recipe.title = recipe_params[:title]
    @recipe.description = recipe_params[:description]
    @recipe.recipe_ingredient_units.destroy_all
    @recipe.make_rius_from_params(recipe_params)
    @recipe.directions.destroy_all
    @recipe.make_directions_from_params(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :description, :recipe_image, :recipe_ingredient_units => [:amount, :ingredient, :unit], :directions => [:description] )
    end 
    
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form_edit.html.erb
<br><br>

<form action="/recipes/<%= @recipe.id %>" method="post" id="recipe_form" role="form">
  <input type="hidden" name="_method" value="PATCH">
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">

  <%= render 'recipes/fields/fields' %>
  
  <input type="submit" value="Save edits" class="btn btn-danger">
</form>

app/views/recipes/_form_new.html.erb
<br><br>

<form action="/recipes" method="post" id="recipe_form" enctype="multipart/form-data" role="form">
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">

  <%= render 'recipes/fields/fields' %>

  <div class="checkbox">
    <label>
      <input type="checkbox" name="add_to_cookbook" value="yes" checked>Add to My Cookbook<br>
    </label>
  </div>
  
  <input type="submit" value="Create recipe!" class="btn btn-danger">
</form>

app/views/recipes/_recipe.html.erb
<div class="col-md-6 col-sm-6">
  <div class="pricing-item">
    <a href="#">
      <%#= image_tag "fruit2.png", class: "img-responsive img-thumbnail", style: "max-width: 250px; float: left;" %>
    <% case recipe.scraped %>
      <% when true %>
        <img src="<%= recipe.recipe_image_file_name %>">
      <% when false %>
        <div class="col-md-6 col-sm-6" style="height:250px;padding-left:0px">
          <% if recipe.recipe_image_file_name == nil %>
            <%= image_tag "chef-icon.jpg", class: "img-responsive" %>
          <% else %>
            <%= image_tag recipe.recipe_image.url(:medium) %>
          <% end %>
        </div>
    <% end %>
    </a>
    <div class="pricing-item-details">
      <h3><%= link_to recipe.title, recipe_path(recipe) %></h3>
      <p>
        <%= recipe.description.first(140) %>
        <%= "..." if recipe.description.length > 140 %>
      </p>
      <%= link_to "View recipe", recipe_path(recipe), class: "btn btn-danger pull-right", style: "position: absolute; bottom: 5px; right: 20px;" %>
      <div class="clearfix"></div>
    </div>
  </div>      
</div>

app/views/recipes/edit.html.erb
<div class="main-content">
  <div class="pricing padd">
    <div class="container">

      <h3>Edit recipe</h3>
      <%= render 'form_edit' %>

    </div>
  </div>
</div>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<div class="main-content">
  <div class="pricing padd">
    <div class="container">
      <h3>The Recipes List</h3>
      <% if logged_in? %>
        <%= link_to 'Add a new recipe!', new_recipe_path, class: "btn btn-success" %>
      <% end %>
      <div class="row">
        <% @recipes.each do |recipe| %>
          <%= render 'recipe', recipe: recipe %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="main-content">
  <div class="pricing padd">
    <div class="container">

      <h3>Add a new recipe</h3>
      <%= render 'form_new' %>

    </div>
  </div>
</div>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<script>
  $(document).ready(function(){
    $("#share a").jqSocialSharer();

    $("#add-to-cookbook").click(function(){
      $.ajax({
        url: "<%= add_recipe_to_cookbook_path %>",
        data: {
          user_id: <%= current_user.id if current_user %>,
          recipe_id: <%= @recipe.id %>
        },
        dataType: "script"
      });
    });
  });  
</script>

<script src="//code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
<script type="text/javascript" charset="utf-8">
  $(window).load(function() {


      messyChef.init();


    $('.flexslider').flexslider({
      slideshow: false
    });
  });

  window.onbeforeunload = function (e) {
    messyChef.stop();
  };
  
  $(function() {
    var progressTimer,
      progressbar = $( "#progressbar" ),
      progressLabel = $( ".progress-label" ),
      dialogButtons = [{
        text: "Cancel Download",
        click: closeDownload
      }],
      dialog = $( "#dialog" ).dialog({
        autoOpen: false,
        closeOnEscape: false,
        resizable: false,
        buttons: dialogButtons,
        open: function() {
          progressTimer = setTimeout( progress, 7000 );
        },
        beforeClose: function() {
          downloadButton.button( "option", {
            disabled: false,
            label: "Start Download"
          });
        }
      }),
      downloadButton = $( "#downloadButton" )
        .button()
        .on( "click", function() {
          $( this ).button( "option", {
            disabled: true,
            label: "Downloading..."
          });
          dialog.dialog( "open" );
        });
 
    progressbar.progressbar({
      value: false,
      change: function() {
        progressLabel.text( "Please give me a quick second" );
      },
      complete: function() {
        progressLabel.text( "Hmm, I'm sorry, you may want to refresh the page." );
        dialog.dialog( "option", "buttons", [{
          text: "Close",
          click: closeDownload
        }]);
        $(".ui-dialog button").last().focus();
      }
    });
 
    function progress() {
      var val = progressbar.progressbar( "value" ) || 0;
 
      progressbar.progressbar( "value", val + Math.floor( Math.random() * 3 ) );
 
      if ( val <= 99 ) {
        progressTimer = setTimeout( progress, 50 );
      }
    }
 
    function closeDownload() {
      clearTimeout( progressTimer );
      dialog
        .dialog( "option", "buttons", dialogButtons )
        .dialog( "close" );
      progressbar.progressbar( "value", false );
      progressLabel
        .text( "MessyChef is interpreting..." );
      downloadButton.focus();
    }
  });
  
</script>


<meta property="og:title" content="<%=@recipe.title%>"/>
<meta property="og:type" content="recipe"/>
<meta property="og:url" content="http://messychef.herokuapp.com/recipes/<%=@recipe.id%>"/>
<meta property="og:image" content=""/>
<meta property="og:site_name" content="MESSYCHEF"/>
<meta property="og:description"
      content="<%=@recipe.description%>"/>




<div class="inner-page padd">
  <div class="blog">
    <div class="container">
      <div class="row">
        <div class="row col-md-8">

          <div class="blog-post">
            <div class="entry">
              <div class="blog-img pull-left">
                <% if @recipe.scraped == true %>
                  <img src="<%= @recipe.recipe_image_file_name %>" class="img-responsive img-thumbnail">
                <% else %>
                  <%= image_tag "chef-icon.jpg", class: "img-responsive" %>
                <% end %>
              </div>

              <h3><a href="#"><%= @recipe.title %></a></h3> 
              <% if @recipe.creator %>
                <p>Recipe created by: <%= @recipe.creator.name %></p>
              <% end %>
              <% if logged_in? && !current_user.recipes.include?(@recipe) %>
                <h3><button class="btn btn-success" id="add-to-cookbook">Add to Cookbook</button></h3>
              <% end %>

              <hr>

              <p>
                <%= @recipe.description %>
                <% if logged_in? %>
                  <div id="share"> 
                    <br><a href="#" class="facebook" data-social='{"type":"facebook", "url":"http://messychef.herokuapp.com/recipes/<%=@recipe.id%>", "text": ""}' title="">&nbsp &nbsp &nbsp Share with friends</a><br>
                  </div>
                <% end %>
              </p>

              <div class="clearfix"></div>
            </div>
          </div>


          <div class="row">
            <div class="recipe">
              <div class="col-md-6 col-sm-6">
                <div class="recipe-item">
                  <h5>Ingredients:</h5>
                  <ul class="list-unstyled">
                    <% @recipe.recipe_ingredient_units.each do |riu| %>
                      <li>
                        <i class="fa fa-check">
                        </i>
                        <% if @recipe.scraped == false %>
                          <%= riu.amount %> <%= Unit.find(riu.unit_id).unit.pluralize(riu.amount) if riu.unit_id %> <%= Ingredient.find(riu.ingredient_id).name %>
                        <% else %>
                          <%= riu.unit.unit %> <%= riu.ingredient.name %>
                        <% end %>
                        <div class="clearfix"></div>
                      </li>
                    <% end %>
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <hr>

          <h5> To scroll to the next direction, say "MessyChef Next", to go back, say "Go Back".</h5>
          <div class="row">
            <div class="col-md-8">
              <div class="recipe-item">
                <div id="interim">Start</div>

                <span id="dialog" title="">
                  
                  <%= image_tag "chef-icon.jpg", style: "margin-left:auto; margin-right: auto;", class: "img-responsive" %>
                  <span class="progress-label">Interpreting your beautiful voice...</span>
                  <span id="progressbar"></span>
                </span>
                <button id="downloadButton">Start Download</button>
              </div>
            </div>
          </div>

          <div class="recipe">
            <h5>Directions:</h5>
          </div>
            
        </div>
      </div>

      <div class="flexslider">
        <ul class="slides">
          <% @recipe.directions.sort_by { |d| d.sequence }.each do |direction| %>
            <li>
              <div>
                <div style="padding: 10px 45px 10px 45px;">
                  <%= direction.sequence %>.
                  <%= direction.description.capitalize[0] + direction.description.slice(1..-1) %>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      </div>

      <div class="row">
        <%= link_to '<< Back', recipes_path, class: "btn btn-danger pull-left" %>
        &nbsp;&nbsp;
        <% if logged_in? && @recipe.creator_id && @recipe.creator_id == current_user.id %>
          <%= link_to 'Edit', edit_recipe_path(@recipe), class: "btn btn-danger" %>
        <% end %>
      </div>

    </div>
  </div>
</div>