config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :cookbooks
  end 
  
  resources :ingredients

  get 'recipes/search' => 'recipes#search'
  resources :recipes

  get 'welcome/hello'
  get 'about/index'

  root :to => "welcome#index"

  post 'recipes/command_detect', to: "recipes#command_detect"

  resources :ingredients, only: [] do
    get :autocomplete_ingredient_name, :on => :collection
  end

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', :as => :signout

  get 'add_recipe_to_cookbook' => 'recipe_cookbooks#add_recipe_to_cookbook', as: "add_recipe_to_cookbook"

end

app/models/cookbook.rb
class Cookbook < ActiveRecord::Base
  belongs_to :user
  has_many :recipe_cookbooks
  has_many :recipes, through: :recipe_cookbooks
end

app/controllers/cookbooks_controller.rb
class CookbooksController < ApplicationController
  before_action :set_cookbook, only: [:show, :edit, :update, :destroy]

  # GET /cookbooks
  # GET /cookbooks.json
  def index
    @cookbooks = Cookbook.all
  end

  # GET /cookbooks/1
  # GET /cookbooks/1.json
  def show
  end

  # GET /cookbooks/new
  def new
    @cookbook = Cookbook.new
  end

  # GET /cookbooks/1/edit
  def edit
  end

  # POST /cookbooks
  # POST /cookbooks.json
  def create
    @cookbook = Cookbook.new(cookbook_params)

    respond_to do |format|
      if @cookbook.save
        format.html { redirect_to @cookbook, notice: 'Cookbook was successfully created.' }
        format.json { render :show, status: :created, location: @cookbook }
      else
        format.html { render :new }
        format.json { render json: @cookbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cookbooks/1
  # PATCH/PUT /cookbooks/1.json
  def update
    respond_to do |format|
      if @cookbook.update(cookbook_params)
        format.html { redirect_to @cookbook, notice: 'Cookbook was successfully updated.' }
        format.json { render :show, status: :ok, location: @cookbook }
      else
        format.html { render :edit }
        format.json { render json: @cookbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cookbooks/1
  # DELETE /cookbooks/1.json
  def destroy
    @cookbook.destroy
    respond_to do |format|
      format.html { redirect_to cookbooks_url, notice: 'Cookbook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cookbook
      @cookbook = Cookbook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cookbook_params
      params[:cookbook]
    end
end

app/helpers/cookbooks_helper.rb
module CookbooksHelper
end

app/views/cookbooks/_form.html.erb
<%= form_for(@cookbook) do |f| %>
  <% if @cookbook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cookbook.errors.count, "error") %> prohibited this cookbook from being saved:</h2>

      <ul>
      <% @cookbook.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cookbooks/edit.html.erb
<h1>Editing cookbook</h1>

<%= render 'form' %>

<%= link_to 'Show', @cookbook %> |
<%= link_to 'Back', cookbooks_path %>

app/views/cookbooks/index.html.erb
<h1>Listing cookbooks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cookbooks.each do |cookbook| %>
      <tr>
        <td><%= link_to 'Show', cookbook %></td>
        <td><%= link_to 'Edit', edit_cookbook_path(cookbook) %></td>
        <td><%= link_to 'Destroy', cookbook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cookbook', new_cookbook_path %>

app/views/cookbooks/new.html.erb
<h1>New cookbook</h1>

<%= render 'form' %>

<%= link_to 'Back', cookbooks_path %>

app/views/cookbooks/show.html.erb
<div class="main-content">
  <div class="pricing padd">
    <div class="container">
      <h3><%= current_user.name %>'s Cookbook</h3>
      <%= link_to 'Add a new recipe!', new_recipe_path, class: "btn btn-success" %>
      <div class="row">
        <% if current_user.recipes %>
          <% current_user.recipes.order("created_at DESC").each do |recipe| %>
            <%= render 'recipes/recipe', recipe: recipe %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>