config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :cookbooks
  end 
  
  resources :ingredients

  get 'recipes/search' => 'recipes#search'
  resources :recipes

  get 'welcome/hello'
  get 'about/index'

  root :to => "welcome#index"

  post 'recipes/command_detect', to: "recipes#command_detect"

  resources :ingredients, only: [] do
    get :autocomplete_ingredient_name, :on => :collection
  end

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', :as => :signout

  get 'add_recipe_to_cookbook' => 'recipe_cookbooks#add_recipe_to_cookbook', as: "add_recipe_to_cookbook"

end

app/views/layouts/_header.html.erb
<div class="header">
  <div class="container">
    <!-- Header top area content -->
    <div class="row">
      <div class="col-md-4 col-sm-5">

        <!-- Link -->
        <%= link_to root_path do %>
          <div class="logo">
            <%= image_tag "chef-icon.jpg", class: "img-responsive" %>
            <!-- Heading -->
            <h1>MessyChef</h1>
          </div>
        <% end %>
      </div>

      <div class="col-md-8 col-sm-7">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-right" role="navigation">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <% if logged_in? %>                
                  <li><%= link_to "My Cookbook", user_cookbook_path(current_user, current_user.cookbooks.first) %></li>
                <% end %>

                <li><%= link_to "Recipes", recipes_path %></li>
                
                <li><%= link_to "About", about_index_path %></li>
              </ul>

              <ul class="nav navbar-nav navbar-right">
                <% if logged_in? %>
                  <li>
                    <%= link_to user_path(current_user) do %>
                      <img src="<%= current_user.image%>">
                    <% end %>
                  </li>
                  <li><%= link_to "Log Out", signout_path %></li>
                <% else %>
                  <li><%= link_to "Log in with Facebook", "auth/facebook" %></li>
                <% end %>
              </ul>  
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
      </div>
    </div>
  </div> <!-- / .container -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Messychef</title>
 <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript">
 </script>
 <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all' %> 
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="wrapper">
  <%= render 'layouts/header' %>
  <p id="notice"><%= notice %></p>
  <%= yield %>
</div>

<div class="footer">
  <div class="footerleft">
   <p> Created at the <a style="color:black;" href="http://flatironschool.com/">Flatiron School</a> by: <br>
     <a style="color:black;" href="http://www.linkedin.com/pub/natalie-arellano/39/b97/131">Natalie Arellano</a>, <a style="color:black;" href="http://www.linkedin.com/in/analuisaperez">Ana Luisa Perez</a>, <br><a style="color:black;" href="http://www.linkedin.com/in/benjaminshore">Ben Shore</a>, and <a style="color:black;" href="http://www.linkedin.com/in/kriscroes">Kris Croes</a></p>
  </div>
 
  <div class="footerright">
    <p>Powered by <a style="color:black;" href="https://wit.ai">Wit.AI</a></p>
  </div>  
</div>


</body>
</html>